<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = [
            ['id' => 1, 'name' => 'Immobilier', 'type_id' => 1, 'icon' => 'fa-home'],
            ['id' => 2, 'name' => 'Véhicules', 'type_id' => 2, 'icon' => 'fa-car'],
            ['id' => 3, 'name' => 'Bricolage', 'type_id' => 3, 'icon' => 'fa-tools'],
            ['id' => 4, 'name' => 'Multimédia', 'type_id' => 4, 'icon' => 'fa-desktop'],
            ['id' => 5, 'name' => 'Mode', 'type_id' => 5, 'icon' => 'fa-tshirt'],
            ['id' => 6, 'name' => 'Maison', 'type_id' => 6, 'icon' => 'fa-home'],
            ['id' => 7, 'name' => 'Jardin & Plantes', 'type_id' => 7, 'icon' => 'fa-seedling'],
            ['id' => 8, 'name' => 'Librairie & Papeterie', 'type_id' => 1, 'icon' => 'fa-book'],
            ['id' => 9, 'name' => 'Animaux', 'type_id' => 2, 'icon' => 'fa-paw'],
            ['id' => 10, 'name' => 'Alimentation', 'type_id' => 3, 'icon' => 'fa-apple-alt'],
            ['id' => 11, 'name' => 'Sports & Loisirs', 'type_id' => 4, 'icon' => 'fa-football-ball'],
            ['id' => 12, 'name' => 'Beauté & Bien-être', 'type_id' => 5, 'icon' => 'fa-spa'],
            ['id' => 13, 'name' => 'Enfance', 'type_id' => 6, 'icon' => 'fa-child'],
            ['id' => 14, 'name' => 'Art & Spectacle', 'type_id' => 7, 'icon' => 'fa-paint-brush'],
            ['id' => 15, 'name' => 'Collection', 'type_id' => 1, 'icon' => 'fa-archway'],
            ['id' => 16, 'name' => 'Billetterie', 'type_id' => 2, 'icon' => 'fa-ticket-alt'],
            ['id' => 17, 'name' => 'Matériel professionnel', 'type_id' => 3, 'icon' => 'fa-briefcase'],
            ['id' => 18, 'name' => 'CD, Vinyles & Cassettes', 'type_id' => 4, 'icon' => 'fa-compact-disc'],
            ['id' => 19, 'name' => 'Seniors & Handicap', 'type_id' => 5, 'icon' => 'fa-wheelchair'],
            ['id' => 20, 'name' => 'Emploi', 'type_id' => 6, 'icon' => 'fa-briefcase'],
            ['id' => 21, 'name' => 'Divers', 'type_id' => 7, 'icon' => 'fa-cubes'],
            ['id' => 22, 'name' => 'Langage & Culture', 'type_id' => 1, 'icon' => 'fa-language'],
            ['id' => 23, 'name' => 'Scolaire', 'type_id' => 2, 'icon' => 'fa-book'],
            ['id' => 24, 'name' => 'Vacances & Week-end', 'type_id' => 3, 'icon' => 'fa-sun'],
            ['id' => 25, 'name' => 'Evenements', 'type_id' => 4, 'icon' => 'fa-calendar'],
        ];

        $subcategories = [
            ['id' => 285,'name' => 'Maison', 'parent_id' => 1],
            ['id' => 284, 'name' => 'Appartements', 'parent_id' => 1],
            ['id' => 283,'name' => 'Parking & Garage', 'parent_id' => 1],
            ['id' => 282, 'name' => 'Terrain', 'parent_id' => 1],
            ['id' => 281, 'name' => 'Chambre', 'parent_id' => 1],
            ['id' => 280, 'name' => 'Chalet', 'parent_id' => 1],
            ['id' => 279, 'name' => 'Propriété', 'parent_id' => 1],
            ['id' => 278, 'name' => 'Commerce', 'parent_id' => 1],
            ['id' => 277, 'name' => 'Bureau', 'parent_id' => 1],
            ['id' => 276, 'name' => 'Programme Neuf', 'parent_id' => 1],
            ['id' => 275, 'name' => 'Château', 'parent_id' => 1],
            ['id' => 274, 'name' => 'Immeuble', 'parent_id' => 1],
            ['id' => 26, 'name' => 'Logemenent social', 'parent_id' => 1],
            ['id' => 27, 'name' => 'Autres', 'parent_id' => 1],
            ['id' => 28, 'name' => 'Voiture', 'parent_id' => 2],
            ['id' => 29, 'name' => 'Motors & Scooters', 'parent_id' => 2],
            ['id' => 30, 'name' => 'Caravaning', 'parent_id' => 2],
            ['id' => 31, 'name' => 'Utilitaires', 'parent_id' => 2],
            ['id' => 32, 'name' => 'Nautirisme', 'parent_id' => 2],
            ['id' => 33, 'name' => 'Cyclisme', 'parent_id' => 2],
            ['id' => 34, 'name' => 'Equipements auto', 'parent_id' => 2],
            ['id' => 35, 'name' => 'Equipements moto & scooter', 'parent_id' => 2],
            ['id' => 36, 'name' => 'Equipements caravaning', 'parent_id' => 2],
            ['id' => 37, 'name' => 'Equipements nautisme', 'parent_id' => 2],
            ['id' => 38, 'name' => 'Equipements cycliste', 'parent_id' => 2],
            ['id' => 39, 'name' => 'NVEI', 'parent_id' => 2],
            ['id' => 40, 'name' => 'Autres', 'parent_id' => 2],
            ['id' => 41, 'name' => 'Peinture & Droguerie', 'parent_id' => 3],
            ['id' => 42, 'name' => 'Outillage & Quincaillerie', 'parent_id' => 3],
            ['id' => 43, 'name' => 'Electricité & Domotique', 'parent_id' => 3],
            ['id' => 44, 'name' => 'Chauffage, Climatisation & Plomberie', 'parent_id' => 3],
            ['id' => 45, 'name' => 'Ménuiserie', 'parent_id' => 3],
            ['id' => 46, 'name' => 'Revêtements de sol', 'parent_id' => 3],
            ['id' => 47, 'name' => 'Matériaux & Construction', 'parent_id' => 3],
            ['id' => 48, 'name' => 'Sécurité', 'parent_id' => 3],
            ['id' => 49, 'name' => 'Objets connectés', 'parent_id' => 4],
            ['id' => 50, 'name' => 'Smartphone', 'parent_id' => 4],
            ['id' => 51, 'name' => 'Imformatique & Tablette', 'parent_id' => 4],
            ['id' => 52, 'name' => 'TV, Image & Son', 'parent_id' => 4],
            ['id' => 53, 'name' => 'Console & Jeux Vidéo', 'parent_id' => 4],
            ['id' => 54, 'name' => 'Autres', 'parent_id' => 4],
            ['id' => 55, 'name' => 'Vêtements Femme', 'parent_id' => 5],
            ['id' => 56, 'name' => 'Vêtements Homme', 'parent_id' => 4],
            ['id' => 57, 'name' => 'Vêtements Fille', 'parent_id' => 5],
            ['id' => 58, 'name' => 'Vêtements Garçon', 'parent_id' => 5],
            ['id' => 59, 'name' => 'Chaussures', 'parent_id' => 5],
            ['id' => 60, 'name' => 'Lingerie', 'parent_id' => 5],
            ['id' => 61, 'name' => 'Maroquenerie, Sacs & Accessoires', 'parent_id' => 5],
            ['id' => 62, 'name' => 'Montres, Bijoux & Lunettes', 'parent_id' => 5],
            ['id' => 63, 'name' => 'Autres', 'parent_id' => 5],
            ['id' => 64, 'name' => 'Meubles, Rangements & Dressing', 'parent_id' => 6],
            ['id' => 65, 'name' => 'Decoration', 'parent_id' => 6],
            ['id' => 66, 'name' => 'Literie', 'parent_id' => 6],
            ['id' => 67, 'name' => 'Luminaire & Eclairage', 'parent_id' => 6],
            ['id' => 68, 'name' => 'Cuisine & Electroménager', 'parent_id' => 6],
            ['id' => 69, 'name' => 'Art de table, Vaisselle & Ustensiles', 'parent_id' => 6],
            ['id' => 70, 'name' => 'Salle de bains', 'parent_id' => 6],
            ['id' => 71, 'name' => 'Linge de maison & Textile', 'parent_id' => 6],
            ['id' => 72, 'name' => 'Appareils électroniques', 'parent_id' => 6],
            ['id' => 73, 'name' => 'Equipements de sécurité', 'parent_id' => 6],
            ['id' => 74, 'name' => 'Peinture & Droguerie', 'parent_id' => 6],
            ['id' => 75, 'name' => 'Chuaffage, Climatisation & Plomberie', 'parent_id' => 6],
            ['id' => 76, 'name' => 'Revêtements de sol', 'parent_id' => 6],
            ['id' => 77, 'name' => 'Matériels médical & Accessoires', 'parent_id' => 6],
            ['id' => 79, 'name' => 'Autres', 'parent_id' => 6],
            ['id' => 78, 'name' => 'Plantes d\'interieur', 'parent_id' => 7],
            ['id' => 80, 'name' => 'Plantes d\'exterieur', 'parent_id' => 7],
            ['id' => 81, 'name' => 'Graines & Bulbes', 'parent_id' => 7],
            ['id' => 82, 'name' => 'Plantes & Bouquets artificiles', 'parent_id' => 7],
            ['id' => 83, 'name' => 'Terreaux & Engrais', 'parent_id' => 7],
            ['id' => 84, 'name' => 'Pots & Jardinières', 'parent_id' => 7],
            ['id' => 85, 'name' => 'Barbecue & Planchas', 'parent_id' => 7],
            ['id' => 86, 'name' => 'Mobilier & Decoration', 'parent_id' => 7],
            ['id' => 87, 'name' => 'Gazon naturels & Artificiles', 'parent_id' => 7],
            ['id' => 88, 'name' => 'Portails, Occultans & Clôtures', 'parent_id' => 7],
            ['id' => 89, 'name' => 'Pavés, Dallages & Bordures', 'parent_id' => 7],
            ['id' => 90, 'name' => 'Serre, Abris & Rangements', 'parent_id' => 7],
            ['id' => 91, 'name' => 'Piscine, Jacuzzi & Jeux plein air', 'parent_id' => 7],
            ['id' => 92, 'name' => 'Bassins & Fontaines', 'parent_id' => 7],
            ['id' => 93, 'name' => 'Traitements & Soins', 'parent_id' => 7],
            ['id' => 94, 'name' => 'Anti-nuisibles', 'parent_id' => 7],
            ['id' => 95, 'name' => 'Lumière & Eclairage', 'parent_id' => 7],
            ['id' => 96, 'name' => 'Arrosoirs & Accessoires', 'parent_id' => 7],
            ['id' => 97, 'name' => 'Outillage & Materiel', 'parent_id' => 7],
            ['id' => 98, 'name' => 'Arrosoirs & Accessoires', 'parent_id' => 7],
            ['id' => 99, 'name' => 'Autres', 'parent_id' => 7],
            ['id' => 100, 'name' => 'Littérature', 'parent_id' => 8],
            ['id' => 101, 'name' => 'Bien-être & Vie pratique', 'parent_id' => 8],
            ['id' => 102, 'name' => 'Loisirs, Nature & Voyages', 'parent_id' => 8],
            ['id' => 103, 'name' => 'Arts, Société & Science humaines', 'parent_id' => 8],
            ['id' => 104, 'name' => 'Jeunesse', 'parent_id' => 8],
            ['id' => 105, 'name' => 'Bande dessinées & Humour', 'parent_id' => 8],
            ['id' => 106, 'name' => 'Scolaire & Pédagogie', 'parent_id' => 8],
            ['id' => 107, 'name' => 'Entreprise, Emploi, Droit & Economie', 'parent_id' => 8],
            ['id' => 108, 'name' => 'Médecine, Sciences & Techniques', 'parent_id' => 8],
            ['id' => 109, 'name' => 'Langues & Livres en VO', 'parent_id' => 8],
            ['id' => 110, 'name' => 'Religion', 'parent_id' => 8],
            ['id' => 111, 'name' => 'E-books', 'parent_id' => 8],
            ['id' => 112, 'name' => 'Dictionnaires', 'parent_id' => 8],
            ['id' => 113, 'name' => 'Calculatrices', 'parent_id' => 8],
            ['id' => 114, 'name' => 'Agendas', 'parent_id' => 8],
            ['id' => 115, 'name' => 'Maroquinerie sccolaire', 'parent_id' => 8],
            ['id' => 116, 'name' => 'Petites fournitures', 'parent_id' => 8],
            ['id' => 117, 'name' => 'Classement', 'parent_id' => 8],
            ['id' => 118, 'name' => 'Ecriture & Encre', 'parent_id' => 8],
            ['id' => 119, 'name' => 'Cahiers, Feuilles & Bloc-Notes', 'parent_id' => 8],
            ['id' => 120, 'name' => 'Coloriage & Dessin', 'parent_id' => 8],
            ['id' => 121, 'name' => 'Autres', 'parent_id' => 8],
            ['id' => 122, 'name' => 'Alimentation', 'parent_id' => 9],
            ['id' => 123, 'name' => 'Equipements & Accéssoires', 'parent_id' => 9],
            ['id' => 124, 'name' => 'Santé', 'parent_id' => 9],
            ['id' => 125, 'name' => 'Autres', 'parent_id' => 9],
            ['id' => 126, 'name' => 'Boissons', 'parent_id' => 10],
            ['id' => 127, 'name' => 'Fruits & Légumes', 'parent_id' => 10],
            ['id' => 128, 'name' => 'Céréales & Féculents', 'parent_id' => 10],
            ['id' => 129, 'name' => 'Produits laitiers', 'parent_id' => 10],
            ['id' => 130, 'name' => 'Viande, Poisson & Oeuf', 'parent_id' => 10],
            ['id' => 131, 'name' => 'Corps gras', 'parent_id' => 10],
            ['id' => 132, 'name' => 'Sucre', 'parent_id' => 10],
            ['id' => 133, 'name' => 'Bio', 'parent_id' => 10],
            ['id' => 134, 'name' => 'Repas', 'parent_id' => 10],
            ['id' => 135, 'name' => 'Equipements de cuisine & Accessoires', 'parent_id' => 10],
            ['id' => 136, 'name' => 'Equipements agricole & Accessoires', 'parent_id' => 10],
            ['id' => 137, 'name' => 'Autres', 'parent_id' => 10],
            ['id' => 138, 'name' => 'Fitness & Musculation', 'parent_id' => 11],
            ['id' => 139, 'name' => 'Balle & Ballon', 'parent_id' => 11],
            ['id' => 140, 'name' => 'Combat', 'parent_id' => 11],
            ['id' => 141, 'name' => 'Animalier', 'parent_id' => 11],
            ['id' => 142, 'name' => 'Glisse', 'parent_id' => 11],
            ['id' => 143, 'name' => 'Détente', 'parent_id' => 11],
            ['id' => 144, 'name' => 'Chorégraphique', 'parent_id' => 11],
            ['id' => 145, 'name' => 'Montagne', 'parent_id' => 11],
            ['id' => 146, 'name' => 'Cible', 'parent_id' => 11],
            ['id' => 147, 'name' => 'Créatif', 'parent_id' => 11],
            ['id' => 148, 'name' => 'Précision', 'parent_id' => 11],
            ['id' => 149, 'name' => 'Extrême', 'parent_id' => 11],
            ['id' => 150, 'name' => 'Réflexion & Intellectuel', 'parent_id' => 11],
            ['id' => 151, 'name' => 'Acrobatique', 'parent_id' => 11],
            ['id' => 152, 'name' => 'Aquatique', 'parent_id' => 11],
            ['id' => 153, 'name' => 'Virtuel', 'parent_id' => 11],
            ['id' => 154, 'name' => 'Culturel', 'parent_id' => 11],
            ['id' => 155, 'name' => 'Artistique', 'parent_id' => 11],
            ['id' => 156, 'name' => 'Autres', 'parent_id' => 11],
            ['id' => 157, 'name' => 'Maquillage', 'parent_id' => 12],
            ['id' => 158, 'name' => 'Cheveux', 'parent_id' => 12],
            ['id' => 159, 'name' => 'Parfum', 'parent_id' => 12],
            ['id' => 160, 'name' => 'Visage & Corps', 'parent_id' => 12],
            ['id' => 161, 'name' => 'Hygiène & Santé', 'parent_id' => 12],
            ['id' => 162, 'name' => 'Autres', 'parent_id' => 12],
            ['id' => 163, 'name' => 'Poussette', 'parent_id' => 13],
            ['id' => 164, 'name' => 'Siège Auto', 'parent_id' => 13],
            ['id' => 165, 'name' => 'Sommeil', 'parent_id' => 13],
            ['id' => 166, 'name' => 'Décoration', 'parent_id' => 13],
            ['id' => 167, 'name' => 'Alimentation', 'parent_id' => 13],
            ['id' => 168, 'name' => 'Eveil & Jouet', 'parent_id' => 13],
            ['id' => 169, 'name' => 'Toilette', 'parent_id' => 13],
            ['id' => 170, 'name' => 'Sécurité', 'parent_id' => 13],
            ['id' => 171, 'name' => 'Mode Bébé', 'parent_id' => 13],
            ['id' => 172, 'name' => 'Autres', 'parent_id' => 13],
            ['id' => 173, 'name' => 'Peinture', 'parent_id' => 14],
            ['id' => 174, 'name' => 'Sculputure', 'parent_id' => 14],
            ['id' => 175, 'name' => 'Photographie', 'parent_id' => 14],
            ['id' => 176, 'name' => 'Dessin', 'parent_id' => 14],
            ['id' => 177, 'name' => 'Matiériels & Fourniture', 'parent_id' => 14],
            ['id' => 178, 'name' => 'Sonorisation', 'parent_id' => 14],
            ['id' => 179, 'name' => 'Eclairage', 'parent_id' => 14],
            ['id' => 180, 'name' => 'Photo & Vidéo', 'parent_id' => 14],
            ['id' => 181, 'name' => 'Scène & Sécurité', 'parent_id' => 14],
            ['id' => 182, 'name' => 'Electricté', 'parent_id' => 14],
            ['id' => 183, 'name' => 'Rangements', 'parent_id' => 14],
            ['id' => 184, 'name' => 'Outillage', 'parent_id' => 14],
            ['id' => 185, 'name' => 'Consommables', 'parent_id' => 14],
            ['id' => 186, 'name' => 'Déguisement & Maquillage', 'parent_id' => 14],
            ['id' => 187, 'name' => 'Autres', 'parent_id' => 14],
            ['id' => 188, 'name' => 'Pierres, Mineraux & Fossiles', 'parent_id' => 15],
            ['id' => 189, 'name' => 'Peinture, Art & Photo', 'parent_id' => 15],
            ['id' => 190, 'name' => 'Philatélie', 'parent_id' => 15],
            ['id' => 191, 'name' => 'Numismatie( monnaies ) ', 'parent_id' => 15],
            ['id' => 192, 'name' => 'Cartes postales', 'parent_id' => 15],
            ['id' => 193, 'name' => 'Aimants', 'parent_id' => 15],
            ['id' => 194, 'name' => 'Cartes de collection', 'parent_id' => 15],
            ['id' => 195, 'name' => 'Figurines', 'parent_id' => 15],
            ['id' => 196, 'name' => 'Pins', 'parent_id' => 15],
            ['id' => 197, 'name' => 'Vaisselle & Dessous de verre', 'parent_id' => 15],
            ['id' => 198, 'name' => 'Bibelots, Fèves, etc..', 'parent_id' => 15],
            ['id' => 199, 'name' => 'Flacons de parfum', 'parent_id' => 15],
            ['id' => 200, 'name' => 'Véhicules', 'parent_id' => 15],
            ['id' => 201, 'name' => 'Miniatures', 'parent_id' => 15],
            ['id' => 202, 'name' => 'Autres', 'parent_id' => 15],
            ['id' => 203, 'name' => 'Transport', 'parent_id' => 16],
            ['id' => 204, 'name' => 'Concerts', 'parent_id' => 16],
            ['id' => 205, 'name' => 'Théâtre', 'parent_id' => 16],
            ['id' => 206, 'name' => 'Humour', 'parent_id' => 16],
            ['id' => 207, 'name' => 'Sports', 'parent_id' => 16],
            ['id' => 208, 'name' => 'Classique, Opéra & Danse', 'parent_id' => 16],
            ['id' => 209, 'name' => 'Festivals', 'parent_id' => 16],
            ['id' => 210, 'name' => 'Enfants & Famille', 'parent_id' => 16],
            ['id' => 211, 'name' => 'Loisirs', 'parent_id' => 16],
            ['id' => 212, 'name' => 'Séjours', 'parent_id' => 16],
            ['id' => 213, 'name' => 'Gastronomie', 'parent_id' => 16],
            ['id' => 214, 'name' => 'Autres', 'parent_id' => 16],
            ['id' => 215, 'name' => 'Agriculture', 'parent_id' => 17],
            ['id' => 216, 'name' => 'Transport & Manutention', 'parent_id' => 17],
            ['id' => 217, 'name' => 'BTP & Chantier gros-oeuvre', 'parent_id' => 17],
            ['id' => 218, 'name' => 'Seconde oeuvre', 'parent_id' => 17],
            ['id' => 219, 'name' => 'Industrie', 'parent_id' => 17],
            ['id' => 220, 'name' => 'Restauration & Hôtellerie', 'parent_id' => 17],
            ['id' => 221, 'name' => 'Bureautique', 'parent_id' => 17],
            ['id' => 222, 'name' => 'Commerces & Marchés', 'parent_id' => 17],
            ['id' => 223, 'name' => 'Medicales', 'parent_id' => 17],
            ['id' => 224, 'name' => 'Autres', 'parent_id' => 17],
            ['id' => 225, 'name' => 'CD, Vinyles & Cassettes', 'parent_id' => 18],
            ['id' => 226, 'name' => 'DVD, Blu-ray & Films', 'parent_id' => 18],
            ['id' => 227, 'name' => 'Mobilité', 'parent_id' => 19],
            ['id' => 228, 'name' => 'Chambre', 'parent_id' => 19],
            ['id' => 229, 'name' => 'Coussins de positionnement & anti-escarre', 'parent_id' => 19],
            ['id' => 230, 'name' => 'Aide au transfert', 'parent_id' => 19],
            ['id' => 231, 'name' => 'Orthopédie', 'parent_id' => 19],
            ['id' => 232, 'name' => 'Autres', 'parent_id' => 19],
            ['id' => 233, 'name' => 'Vêtements professionels', 'parent_id' => 20],
            ['id' => 234, 'name' => 'Chaussures de sécurité', 'parent_id' => 20],
            ['id' => 235, 'name' => 'Autres', 'parent_id' => 20],
            ['id' => 236, 'name' => 'Autres', 'parent_id' => 21],
            ['id' => 237, 'name' => 'Langue des signes', 'parent_id' => 22],
            ['id' => 238, 'name' => 'Français', 'parent_id' => 22],
            ['id' => 239, 'name' => 'Anglais', 'parent_id' => 22],
            ['id' => 240, 'name' => 'Espagnol', 'parent_id' => 22],
            ['id' => 241, 'name' => 'Italien', 'parent_id' => 22],
            ['id' => 242, 'name' => 'Allemand', 'parent_id' => 22],
            ['id' => 243, 'name' => 'Hindi', 'parent_id' => 22],
            ['id' => 244, 'name' => 'Arabe', 'parent_id' => 22],
            ['id' => 245, 'name' => 'Portugais', 'parent_id' => 22],
            ['id' => 246, 'name' => 'Russe', 'parent_id' => 22],
            ['id' => 247, 'name' => 'Turc', 'parent_id' => 22],
            ['id' => 248, 'name' => 'Bengali', 'parent_id' => 22],
            ['id' => 249, 'name' => 'Japonais', 'parent_id' => 22],
            ['id' => 250, 'name' => 'Autres', 'parent_id' => 22],
            ['id' => 251, 'name' => 'Travail en groupe', 'parent_id' => 23],
            ['id' => 252, 'name' => 'Professeur', 'parent_id' => 23],
            ['id' => 253, 'name' => 'Week-end & Escapade', 'parent_id' => 24],
            ['id' => 254, 'name' => 'Séjours classiques', 'parent_id' => 24],
            ['id' => 255, 'name' => 'Voyage longue durée', 'parent_id' => 24],
            ['id' => 256, 'name' => 'Globe trotting ( ou aventure)', 'parent_id' => 24],
            ['id' => 257, 'name' => 'Transports', 'parent_id' => 25],
            ['id' => 258, 'name' => 'Concerts', 'parent_id' => 25],
            ['id' => 259, 'name' => 'Théatre', 'parent_id' => 25],
            ['id' => 260, 'name' => 'Humour', 'parent_id' => 25],
            ['id' => 261, 'name' => 'Sports', 'parent_id' => 25],
            ['id' => 262, 'name' => 'Spectacles, Carabets & Cirques', 'parent_id' => 25],
            ['id' => 263, 'name' => 'Muséés, Expos & Monuments', 'parent_id' => 25],
            ['id' => 264, 'name' => 'Parcs', 'parent_id' => 25],
            ['id' => 265, 'name' => 'Cinéma', 'parent_id' => 25],
            ['id' => 266, 'name' => 'Salons', 'parent_id' => 25],
            ['id' => 267, 'name' => 'Classique, Opéra & Danse', 'parent_id' => 25],
            ['id' => 268, 'name' => 'Festivals', 'parent_id' => 25],
            ['id' => 269, 'name' => 'Enfants & Famille', 'parent_id' => 25],
            ['id' => 270, 'name' => 'Loisirs', 'parent_id' => 25],
            ['id' => 271, 'name' => 'Séjours', 'parent_id' => 25],
            ['id' => 272, 'name' => 'Gastronomie', 'parent_id' => 25],
            ['id' => 273, 'name' => 'Autres', 'parent_id' => 25],
        
        ];

        Category::insert($categories);
        Category::insert($subcategories);

    }
}
