<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class TypeCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $typeCategories = [
            ['id' => 1, 'type_id' => 4, 'category_id' => 9],
            ['id' => 2, 'type_id' => 1, 'category_id' => 1],
            ['id' => 3, 'type_id' => 1, 'category_id' => 2],
            ['id' => 4, 'type_id' => 1, 'category_id' => 3],
            ['id' => 5, 'type_id' => 1, 'category_id' => 4],
            ['id' => 6, 'type_id' => 1, 'category_id' => 5],
            ['id' => 7, 'type_id' => 1, 'category_id' => 6],
            ['id' => 8, 'type_id' => 1, 'category_id' => 7],
            ['id' => 9, 'type_id' => 1, 'category_id' => 8],
            ['id' => 10, 'type_id' => 1, 'category_id' => 9],
            ['id' => 11, 'type_id' => 1, 'category_id' => 10],
            ['id' => 12, 'type_id' => 1, 'category_id' => 11],
            ['id' => 13, 'type_id' => 1, 'category_id' => 12],
            ['id' => 14, 'type_id' => 1, 'category_id' => 13],
            ['id' => 15, 'type_id' => 1, 'category_id' => 14],
            ['id' => 16, 'type_id' => 1, 'category_id' => 15],
            ['id' => 17, 'type_id' => 1, 'category_id' => 16],
            ['id' => 18, 'type_id' => 1, 'category_id' => 17],
            ['id' => 19, 'type_id' => 1, 'category_id' => 18],
            ['id' => 20, 'type_id' => 1, 'category_id' => 19],
            ['id' => 21, 'type_id' => 1, 'category_id' => 20],
            ['id' => 22, 'type_id' => 1, 'category_id' => 21],
            ['id' => 23, 'type_id' => 3, 'category_id' => 1],
            ['id' => 24, 'type_id' => 3, 'category_id' => 2],
            ['id' => 25, 'type_id' => 3, 'category_id' => 3],
            ['id' => 26, 'type_id' => 3, 'category_id' => 4],
            ['id' => 27, 'type_id' => 3, 'category_id' => 5],
            ['id' => 28, 'type_id' => 3, 'category_id' => 6],
            ['id' => 29, 'type_id' => 3, 'category_id' => 7],
            ['id' => 30, 'type_id' => 3, 'category_id' => 8],
            ['id' => 31, 'type_id' => 3, 'category_id' => 9],
            ['id' => 32, 'type_id' => 3, 'category_id' => 10],
            ['id' => 33, 'type_id' => 3, 'category_id' => 11],
            ['id' => 34, 'type_id' => 3, 'category_id' => 12],
            ['id' => 35, 'type_id' => 3, 'category_id' => 13],
            ['id' => 36, 'type_id' => 3, 'category_id' => 14],
            ['id' => 37, 'type_id' => 3, 'category_id' => 15],
            ['id' => 38, 'type_id' => 3, 'category_id' => 16],
            ['id' => 39, 'type_id' => 3, 'category_id' => 17],
            ['id' => 40, 'type_id' => 3, 'category_id' => 18],
            ['id' => 41, 'type_id' => 3, 'category_id' => 19],
            ['id' => 42, 'type_id' => 3, 'category_id' => 20],
            ['id' => 43, 'type_id' => 3, 'category_id' => 21],
            ['id' => 44, 'type_id' => 7, 'category_id' => 11],
            ['id' => 45, 'type_id' => 7, 'category_id' => 12],
            ['id' => 46, 'type_id' => 7, 'category_id' => 13],
            ['id' => 47, 'type_id' => 7, 'category_id' => 15],
            ['id' => 48, 'type_id' => 7, 'category_id' => 16],
            ['id' => 49, 'type_id' => 7, 'category_id' => 10],
            ['id' => 50, 'type_id' => 7, 'category_id' => 11],
            ['id' => 51, 'type_id' => 7, 'category_id' => 12],
            ['id' => 52, 'type_id' => 7, 'category_id' => 13],
            ['id' => 53, 'type_id' => 7, 'category_id' => 14],
            ['id' => 54, 'type_id' => 7, 'category_id' => 15],
            ['id' => 55, 'type_id' => 7, 'category_id' => 16],
            ['id' => 56, 'type_id' => 7, 'category_id' => 22],
            ['id' => 57, 'type_id' => 7, 'category_id' => 23],
            ['id' => 58, 'type_id' => 7, 'category_id' => 24],
            ['id' => 59, 'type_id' => 7, 'category_id' => 25],
            ['id' => 60, 'type_id' => 7, 'category_id' => 19],
            ['id' => 61, 'type_id' => 7, 'category_id' => 21],
            ['id' => 62, 'type_id' => 5, 'category_id' => 1],
            ['id' => 63, 'type_id' => 5, 'category_id' => 2],
            ['id' => 64, 'type_id' => 5, 'category_id' => 3],
            ['id' => 65, 'type_id' => 5, 'category_id' => 4],
            ['id' => 66, 'type_id' => 5, 'category_id' => 5],
            ['id' => 67, 'type_id' => 5, 'category_id' => 6],
            ['id' => 68, 'type_id' => 5, 'category_id' => 7],
            ['id' => 69, 'type_id' => 5, 'category_id' => 8],
            ['id' => 70, 'type_id' => 5, 'category_id' => 9],
            ['id' => 71, 'type_id' => 5, 'category_id' => 10],
            ['id' => 72, 'type_id' => 5, 'category_id' => 11],
            ['id' => 73, 'type_id' => 5, 'category_id' => 12],
            ['id' => 74, 'type_id' => 5, 'category_id' => 13],
            ['id' => 75, 'type_id' => 5, 'category_id' => 14],
            ['id' => 76, 'type_id' => 5, 'category_id' => 15],
            ['id' => 77, 'type_id' => 5, 'category_id' => 17],
            ['id' => 78, 'type_id' => 5, 'category_id' => 22],
            ['id' => 79, 'type_id' => 5, 'category_id' => 23],
            ['id' => 80, 'type_id' => 5, 'category_id' => 19],
            ['id' => 81, 'type_id' => 5, 'category_id' => 21],
            ['id' => 82, 'type_id' => 6, 'category_id' => 1],
            ['id' => 83, 'type_id' => 6, 'category_id' => 2],
            ['id' => 84, 'type_id' => 6, 'category_id' => 3],
            ['id' => 85, 'type_id' => 6, 'category_id' => 4],
            ['id' => 86, 'type_id' => 6, 'category_id' => 5],
            ['id' => 87, 'type_id' => 6, 'category_id' => 6],
            ['id' => 88, 'type_id' => 6, 'category_id' => 7],
            ['id' => 89, 'type_id' => 6, 'category_id' => 8],
            ['id' => 90, 'type_id' => 6, 'category_id' => 9],
            ['id' => 91, 'type_id' => 6, 'category_id' => 10],
            ['id' => 92, 'type_id' => 6, 'category_id' => 11],
            ['id' => 93, 'type_id' => 6, 'category_id' => 12],
            ['id' => 94, 'type_id' => 6, 'category_id' => 13],
            ['id' => 95, 'type_id' => 6, 'category_id' => 14],
            ['id' => 96, 'type_id' => 6, 'category_id' => 15],
            ['id' => 97, 'type_id' => 6, 'category_id' => 17],
            ['id' => 98, 'type_id' => 6, 'category_id' => 18],
            ['id' => 99, 'type_id' => 6, 'category_id' => 19],
            ['id' => 100, 'type_id' => 6, 'category_id' => 20],
            ['id' => 101, 'type_id' => 6, 'category_id' => 21],
            ['id' => 102, 'type_id' => 2, 'category_id' => 1],
            ['id' => 103, 'type_id' => 2, 'category_id' => 2],
            ['id' => 104, 'type_id' => 2, 'category_id' => 3],
            ['id' => 105, 'type_id' => 2, 'category_id' => 4],
            ['id' => 106, 'type_id' => 2, 'category_id' => 5],
            ['id' => 107, 'type_id' => 2, 'category_id' => 6],
            ['id' => 108, 'type_id' => 2, 'category_id' => 7],
            ['id' => 109, 'type_id' => 2, 'category_id' => 8],
            ['id' => 110, 'type_id' => 2, 'category_id' => 9],
            ['id' => 111, 'type_id' => 2, 'category_id' => 10],
            ['id' => 112, 'type_id' => 2, 'category_id' => 11],
            ['id' => 113, 'type_id' => 2, 'category_id' => 12],
            ['id' => 114, 'type_id' => 2, 'category_id' => 13],
            ['id' => 115, 'type_id' => 2, 'category_id' => 14],
            ['id' => 116, 'type_id' => 2, 'category_id' => 15],
            ['id' => 117, 'type_id' => 2, 'category_id' => 20],
            ['id' => 118, 'type_id' => 2, 'category_id' => 23],
            ['id' => 119, 'type_id' => 2, 'category_id' => 19],
            ['id' => 120, 'type_id' => 2, 'category_id' => 21],
        ];
        
        DB::table('type_category')->insert($typeCategories);        

    }
}
